# Generated by Django 5.1.5 on 2025-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(help_text='Nome completo do cliente.', max_length=100)),
                ('email_cliente', models.EmailField(blank=True, help_text='E-mail do cliente para comunicação.', max_length=254, null=True)),
                ('data_horario_reserva', models.DateTimeField(help_text='Data e hora do agendamento.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('data_horario_reserva', 'status')},
            },
        ),
    ]
