# Generated by Django 5.1.5 on 2025-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_horario_reserva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
