# Generated by Django 5.0.6 on 2025-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_remove_agendamento_bloqueado_agendamento_disponivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
