# Generated by Django 5.1.5 on 2026-01-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_horariobloqueado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_horario_reserva']},
        ),
    ]
